import { IProperty } from "./models/property.model";

export const propertiesData: IProperty[] = [
  {
    id: '1',
    street: 'Beco Casan',
    number: 193,
    neighborhood: 'Beira Rio',
    city: 'Benedito Novo',
    uf: 'Santa Catarina',
    country: 'Brasil',
    bedroom: 2,
    bathroom: 1,
    kitchen: 1,
    spot: 2,
    area: 120,
    externalArea: 400,
    price: 599,
    title: 'Chalé Palmen Haus com banheira de hidromassagem',
    description: 'Um chalé super equipado, moderno e isolado. Pátio grande com gramado, ribeirão artificial, cascata e lareira de jardim, proporcionando um lugar único com vista espetacular das montanhas e rio.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0101.webp',
      'assets/properties/property0102.webp',
      'assets/properties/property0103.webp',
      'assets/properties/property0104.webp',
      'assets/properties/property0105.webp',
    ],
    tags: ['Acampamento', 'No Interior'],
  },
  {
    id: '2',
    street: 'Adílio Inácio de Abreu',
    number: 2059,
    neighborhood: 'Lagoa de Macac',
    city: 'Garopaba',
    uf: 'Santa Catarina',
    country: 'Brasil',
    bedroom: 1,
    bathroom: 1,
    kitchen: 1,
    spot: 1,
    area: 100,
    externalArea: 250,
    price: 290,
    title: 'Vista para o mar e dunas na montanha em Garopaba',
    description: 'Local tranquilo e privativo em meio a natureza, com bosque ao lado e barulho de cachoeira. Vista para o mar e dunas na Costa do Macacu. Estudio completo e charmoso com estacioamento, isolado em meio a natureza exuberante.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0201.webp',
      'assets/properties/property0202.webp',
      'assets/properties/property0203.webp',
      'assets/properties/property0204.webp',
      'assets/properties/property0205.webp',
    ],
    tags: ['Acampamento', 'No Interior'],
  },
  {
    id: '3',
    street: 'Roberto Silveira',
    number: 12,
    neighborhood: 'Ponta Grossa',
    city: 'Paraty',
    uf: 'Rio de Janeiro',
    country: 'Brasil',
    bedroom: 5,
    bathroom: 4,
    kitchen: 2,
    spot: 0,
    area: 180,
    externalArea: 500,
    price: 2830,
    title: 'Casa Ohana Frente Mar Costeira',
    description: 'Relaxe com toda a família nesta acomodação tranquila, com uma vista deslumbrante para a Baia de Paraty. Casa Front-Mar situada na Ponta Grossa - Zona Costeira Acesso somente de barco.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0301.webp',
      'assets/properties/property0302.webp',
      'assets/properties/property0303.webp',
      'assets/properties/property0304.webp',
      'assets/properties/property0305.webp',
    ],
    tags: ['Na Praia', 'No Interior'],
  },
  {
    id: '4',
    street: 'Morgan Hill Rd',
    number: 69,
    neighborhood: 'Long Bay Village',
    city: 'Anguilla',
    uf: 'Território Ultramarino',
    country: 'Inglaterra',
    bedroom: 9,
    bathroom: 10,
    kitchen: 3,
    spot: 10,
    area: 520,
    externalArea: 1200,
    price: 37519,
    title: 'Santosha Estate, resort privado só para você',
    description: 'Entre na felicidade caribenha em nosso enclave ultra privado à beira-mar, Santosha Villa Estate, na isolada Long Bay Beach. Santosha é mais que uma vila, uma experiência. É um resort privado de 5 estrelas à beira-mar que vocês têm só para vocês.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0401.webp',
      'assets/properties/property0402.webp',
      'assets/properties/property0403.webp',
      'assets/properties/property0404.webp',
      'assets/properties/property0405.webp',
    ],
    tags: ['Na Praia', 'Com Piscina'],
  },
  {
    id: '5',
    street: 'Calle Puerto',
    number: 24,
    neighborhood: 'Los Cajuiles',
    city: 'La Romana',
    uf: 'La Romana',
    country: 'República Dominicana',
    bedroom: 12,
    bathroom: 14,
    kitchen: 4,
    spot: 6,
    area: 220,
    externalArea: 480,
    price: 49558,
    title: 'Caleton 24: à beira-mar com praia, piscina, equipe completa',
    description: 'Esta vila inclui um chef particular, um mordomo, um barman, um garçom, limpeza diária e um gerente de vila no local. Desfrute de uma série de serviços exclusivos de 5 estrelas e acesso a algumas das melhores comodidades do Caribe.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0501.webp',
      'assets/properties/property0502.webp',
      'assets/properties/property0503.webp',
      'assets/properties/property0504.webp',
      'assets/properties/property0505.webp',
    ],
    tags: ['Na Praia', 'Com Piscina', 'Casas Modernas'],
  },
  {
    id: '6',
    street: 'Paulin Chipotel',
    number: 48,
    neighborhood: 'Douville',
    city: 'Sainte-Anne',
    uf: 'Grande-Terre',
    country: 'Guadalupe',
    bedroom: 6,
    bathroom: 6,
    kitchen: 1,
    spot: 4,
    area: 200,
    externalArea: 360,
    price: 5256,
    title: 'Villa Pauline vista para o mar perto da praia',
    description: 'Localizada no alto de uma área tranquila e residencial no centro de Sainte-Anne, esta nova casa é perfeita para momentos familiares memoráveis. As lojas mais próximas ficam a 5 minutos a pé.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0601.webp',
      'assets/properties/property0602.webp',
      'assets/properties/property0603.webp',
      'assets/properties/property0604.webp',
      'assets/properties/property0605.webp',
    ],
    tags: ['Na Praia', 'Com Piscina', 'Casas Modernas'],
  },
  {
    id: '7',
    street: 'Baldy',
    number: 38,
    neighborhood: 'Baldy',
    city: 'Breckenridge',
    uf: 'Colorado',
    country: 'Estados Unidos',
    bedroom: 4,
    bathroom: 4,
    kitchen: 1,
    spot: 4,
    area: 220,
    externalArea: 470,
    price: 3716,
    title: 'Three Sisters Lookout',
    description: 'Aproveite as majestosas Montanhas Rochosas e o ambiente clássico de Breckenridge de uma forma novinha em folha no Three Sisters Lookout.',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0701.webp',
      'assets/properties/property0702.webp',
      'assets/properties/property0703.webp',
      'assets/properties/property0704.webp',
      'assets/properties/property0705.webp',
    ],
    tags: ['Acampamento', 'No Interior', 'Nas Montanhas'],
  },
  {
    id: '8',
    street: 'Aquitania-Tota',
    number: 22,
    neighborhood: 'La Custodia',
    city: 'Aquitania',
    uf: 'Boyacá',
    country: 'Colômbia',
    bedroom: 1,
    bathroom: 1,
    kitchen: 1,
    spot: 1,
    area: 50,
    externalArea: 400,
    price: 418,
    title: 'Domos Blue, Maxi Blue',
    description: 'Cúpula em um terreno rural na Península do Lago Tota, clima frio, atmosfera Páramo cercada pela natureza e cultivos imersos na beleza da cultura Boyacense com uma bela vista para o Lago Tota e para o município de Aquitaine',
    contactNumber: '015997426807',
    email: 'celsogabrielf@gmail.com',
    url: [
      'assets/properties/property0801.webp',
      'assets/properties/property0802.webp',
      'assets/properties/property0803.webp',
      'assets/properties/property0804.webp',
      'assets/properties/property0805.webp',
    ],
    tags: ['Acampamento', 'No Interior', 'Nas Montanhas'],
  },
];

export const tags: any[] = [
  { name: 'Na Praia', src: 'assets/icons/beach.jpg', active: false },
  { name: 'Acampamento', src: 'assets/icons/camping.jpg', active: false },
  { name: 'No Interior', src: 'assets/icons/countryHouse.jpg', active: false },
  { name: 'Casas Modernas', src: 'assets/icons/house.jpg', active: false },
  { name: 'Nas Montanhas', src: 'assets/icons/mountains.jpg', active: false },
  { name: 'Com Piscina', src: 'assets/icons/pool.jpg', active: false },
]

export const users: any[] = [
  {
    name: "Celso Prado",
    email: "celsogabrielf@gmail.com",
    password: "$2a$10$gw55KLfO1/MaMq30YKBqY.TDY9t2mTkg6MyM61Kw9oZ5qZTcZ9xmO"
  }
]